-- Drop Junction Tables First
DROP TABLE IF EXISTS item_types CASCADE;
DROP TABLE IF EXISTS item_tags CASCADE;
DROP TABLE IF EXISTS item_notes CASCADE;
DROP TABLE IF EXISTS item_conditions CASCADE;
DROP TABLE IF EXISTS item_spells CASCADE;
DROP TABLE IF EXISTS item_effects CASCADE;

DROP TABLE IF EXISTS spell_tags CASCADE;
DROP TABLE IF EXISTS spell_conditions CASCADE;
DROP TABLE IF EXISTS spell_damagetypes CASCADE;
DROP TABLE IF EXISTS spell_classes CASCADE;

DROP TABLE IF EXISTS item_image_urls CASCADE;
DROP TABLE IF EXISTS product_image_urls CASCADE;
DROP TABLE IF EXISTS spell_image_urls CASCADE;
DROP TABLE IF EXISTS user_image_urls CASCADE;

-- Drop Main Tables Second
DROP TABLE IF EXISTS image_urls CASCADE;
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS conditions CASCADE;
DROP TABLE IF EXISTS damagetypes CASCADE;
DROP TABLE IF EXISTS rpg_classes CASCADE;

DROP TABLE IF EXISTS wishlists CASCADE;
DROP TABLE IF EXISTS itemsources CASCADE;
DROP TABLE IF EXISTS image_urls CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS effects CASCADE;
DROP TABLE IF EXISTS TTRPGS CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS spells CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS products CASCADE;
